services:
  nginx:
    image: nginx:1.29.4-alpine
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - app

  app:
    build:
      ./docker/php
    volumes:
      - ./src:/var/www/html

  # db:
  #   image: mysql:9.6
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATA_BASE: laravel
  #     MYSQL_USER: laravel
  #     MYSQL_PASSWORD: laravel
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - dbdata:/var/lib/mysql